worker_processes = "auto"
port = 80

[events]
worker_connections = 512

[general]
CLIENT_SERVER = "dev.reticulum.io"
API_SERVER = "dev.reticulum.io"
cors_proxy_server = "cors-proxy-dev.reticulum.io"
thumbnail_server = "nearspark-dev.reticulum.io"
non_cors_proxy_domains = "localhost,dev.reticulum.io"
base_assets_path = "/"
sentry_dsn = ""
ga_tracking_id = ""
is_moz = false

[deploy]
type = "serve"

[server]
